import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Let's Study about Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to JinWoo&apos;s NextJS Page!</h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a
            href="https://dlwlsdn201.github.io/ToDoList/"
            className={styles.card}
          >
            <h2>투두리스트</h2>
            <p>
              {' '}
              HTML5, CSS3, Vanila JS들로 구현한 투두 리스트 프로젝트 입니다.
            </p>
          </a>

          <a
            href="https://dlwlsdn201.github.io/movie-rank-page/"
            className={styles.card}
          >
            <h2>박스오피스 영화 랭킹 사이트</h2>
            <p>
              Typescript를 기반으로 구현한 박스오피스 영화 랭킹 서비스
              사이트입니다.
            </p>
          </a>
          <Link href="/test">
            <a className={styles.card}>
              <h2>Here I am</h2>
              <p>여기는 테스트용 페이지입니다.</p>
            </a>
          </Link>
          <a
            href="https://dlwlsdn201.github.io/portpolio-developing/"
            className={styles.card}
          >
            <h2>포트폴리오 페이지</h2>
            <p>
              fullPage scroll 애니메이션을 기반으로 구현한 포트폴리오
              페이지입니다 .
            </p>
          </a>
          <Link href="/test">
            <a className={styles.card}>
              <h2>Test</h2>
              <p>
                Instantly deploy your Next.js site to a public URL with Vercel.
              </p>
            </a>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
